name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python Code/wine-master/train.py
          
          echo "****Welcome to Model Metrics****"
          cat metrics.txt >> report.md
          
          echo "Data Visualization" >> report.md
          main publish feature_importance.png --md >> report.md
          main publish residuals.png --md >> report.md
          
          
          main-send-comment report.md
